### ISSUE TITLE
Screenshot in the README

### ISSUE THREAD

**Issue by eddiejaoude** [AcornHack/joodle-dump#1]
I saw a little demo yesterday & it was great. Can you add a screenshot to the `README.md` please :smile:

**Comment by amy-phillips** [comment]
Done!

**Comment by MiaCurrid** [comment]
What is the code to set up the cmd. Can you please tell me

**Comment by GeorginaWilcox** [comment]
To run the code? You should be able to double click on the Python file
(it's called doodle.py) and it will just run. But if there is an error it
might crash immediately and you won't know where the error is...

So you can open a cmd prompt:
1. either hit "windows key + r" (for run), or click on the windows start
   icon, and then
2. type "cmd" and press enter
3. Now we need to find the path to your file -- if you navigate in windows
   explorer to folder that has the doodle.py file, the path is at the top
   (kind of like the address bar in Internet Explorer). You can click on it
   and then copy and paste it.
4. In the cmd prompt, type "cd" and then paste the path, and press enter.
   It should be something a bit like:

> cd C:\Users\Mia\Documents\GitHub\joodle-dump
> 1. If you type "dir" now and press enter, do you see a list of files,
>    including doodle.py?
> 2. Type "doodle.py" at the command prompt and hit enter... it should
>    start...

Sorry I don't really use windows so those weren't great instructions. Maybe
Amy will be able to give better instructions. I hope you can show your
parents what you made today, that would be cool!

Georgina

**Comment by amy-phillips** [comment]
Yes, do that, but  I think you need to type in the command prompt

C:\Python34\python.exe doodle.py

Does that work?

   Amy

**Comment by eddiejaoude** [comment]
This is great! Logging **Questions** and **Answers**, which can help others too! #transparentCollaboration

_I am going to Tweet it now_ :+1:
